// Code generated by Prismic. DO NOT EDIT.

import Hero from "./Hero";
import ImageAndText from "./ImageAndText";
import ProductGrid from "./ProductGrid";

export const components = {
	hero: Hero,
	image_and_text: ImageAndText,
	product_grid: ProductGrid
};