import type { Metadata } from "next";
import "./globals.css";

import { Bowlby_One_SC, DM_Mono } from "next/font/google";
import { Header } from "@/components/Header";
import { SVGFilters } from "@/components/SVGFilters";
import { Footer } from "@/components/Footer";

const bowlby = Bowlby_One_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bowlby-sc",
  weight: "400",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-mono",
  weight: "500",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${bowlby.variable} ${dmMono.variable} h-full antialiased font-medium text-zinc-800`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          <Header />
          {children}
          <Footer />
        </main>
        <SVGFilters />
      </body>
    </html>
  );
}
